<?php
// Plugin definition
$plugin = array(
  'title' => t('cms landing'),
  'icon' => 'cms_landing.png',
  'category' => t('CMSApsjob'),
  'theme' => 'cms_landing',
  'regions' => array(
    'content_banner' => t('Content Banner'),
    'sub_nav' => t('Sub Navigation'),
    'content_feature' => t('Content Feature'),
    'content_main' => t('Content Main'),
    'content_first' => t('Content First'),
    'content_second' => t('Content Second'),
    'content_second_sub' => t('Content Second Sub'),
    'content_third' => t('Content Third'),
    'content_fourth' => t('Content Fourth'),
    'content_fifth' => t('Content Fifth'),
    'content_sixth' => t('Content Sixth'),
  ),
);
