<?php

require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes.utils.inc";

require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create.form.inc";
require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create.validate.inc";
require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create.submit.inc";

require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create_free_outcomes.form.inc";
require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create_free_outcomes.validate.inc";
require_once drupal_get_path("module", "apsjobs_outcomes") . "/includes/apsjobs_outcomes_create_free_outcomes.submit.inc";

/**
 * Implements hook_menu()
 */
function apsjobs_outcomes_menu() {
  $items = array();

  $items['outcome/approved/%'] = array(
    'title' => 'APSJobs Outcomes Approve',
    'page callback' => 'apsjobs_outcomes_change_state',
    'page arguments' => array(1, 2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

	$items['outcome/rejected/%'] = array(
    'title' => 'APSJobs Outcomes Reject',
    'page callback' => 'apsjobs_outcomes_change_state',
    'page arguments' => array(1, 2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_init()
 */
function apsjobs_outcomes_init() {
	$options = array(
    'scope' => 'footer'
  );
  drupal_add_js(drupal_get_path('module', 'apsjobs_outcomes') .'/js/apsjobs_outcomes.js', $options);
}


function apsjobs_forms_block_info(){
	$block = array();

	$block['apsjob_create_outcome'] = array(
    'info' => t('APSJobs Create Outcomes'),
  );

  $block['apsjob_create_free_outcome'] = array(
    'info' => t('APSJobs Create Free Outcomes'),
  );

  return $block;
}

function apsjobs_forms_block_view($delta = ''){
	$block = array();

	switch ($delta) {
		case 'apsjob_create_outcome':
			$form = drupal_get_form('apsjobs_outcomes_create_form');
      //$form = drupal_get_form('apsjobs_outcomes_action_an_existing_notice_form');
			$block['content'] = $form;
			break;
    case 'apsjob_create_free_outcome':
      //$form = drupal_get_form('apsjobs_outcomes_create_free_outcomes_form');
      $form = drupal_get_form('apsjobs_outcomes_create_form');
      $block['content'] = $form;
      break;
	}
	return $block;
}

/**
 * Implements hook_mail().
 */
function apsjobs_outcomes_mail($key, &$message, $params){
  switch ($key) {
    case "apsjobs_mail":
      // Set the mail content type to html to send an html e-mail (optional).
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';

      // Grab the subject and body from params and add it to the message.
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body']; // Drupal 7
      break;
  }
}
